name: Make Repository

on:
  push:
    branches:
      - master
      - debug
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build_repository:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time
      uses: ccccmagicboy/get_datetime@master
      id: datetime

    - name: Build Packages
      uses: kopp/build-aur-packages@v1
      with:
        packages: >
          ton-git
          alx-wol-dkms
          aria2-fast
          bun
          cxxmatrix-git
          telegram-desktop-bin
          nerd-fonts-complete
        
    - name: List generated Files
      run: ls -1 > ${{ github.workspace }}/files.txt
      
    - name: Remove current release
      uses: kopp/action-delete-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: aurbuilder
        
    - name: Upload Files to Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: aurbuilder
        name: Build ${{ github.run_number }} at ${{ steps.datetime.outputs.datetime_str }}
        files: |
          ${{ github.workspace }}/*
        draft: false
        prerelease: false
